//Script GUID:605a023c-273a-462d-b73e-ea551b1dbee9
//Used for tracking history
#IF (LOCAL)
#DECLARE input_tweet_path string = @"D:\Download\recent-filtered-tweets9-11.ss";
#DECLARE output string = @"D:\Download\recent-filtered-tweets9-11-follower5000.tsv";
#ELSE
#DECLARE input_tweet_path string = @"/local/Realtime/SocialVoice/recent-filtered-tweets-2.ss";
#DECLARE output string = @"/local/Realtime/SocialVoice/recent-filtered-tweets-2-index.ss";
#ENDIF

tw1 = SSTREAM @input_tweet_path;
tw2 =
    SELECT *
    FROM tw1
    WHERE uFollowersCount > 5000;

OUTPUT tw1
TO @output;